version: "3.8"

networks:
  test_network:
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      encrypted: "true"

services:
  client:
    image: mesoform/net-tools:latest
    command: curl -iL https://dl-cdn.alpinelinux.org/alpine/v3.14/main
    networks:
      test_network:
    labels:
      ENV: test
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.storage == one
