version: "3.8"

networks:
  test_network:
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      encrypted: "true"

services:
  server:
    image: mesoform/net-tools:latest
    command: nc -lv4p 80
    networks:
      test_network:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.zone==a
  client:
    image: mesoform/net-tools:latest
    command: nc -Nv server 80
    networks:
      net_tools_test:
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.zone==b
